name: AI Fix
on:
  issues:
    types: [labeled]

jobs:
  claude-code-action:
    if: contains(github.event.label.name, 'ai-fix-easy') || contains(github.event.label.name, 'ai-fix-hard')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get issue details
        id: issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            core.setOutput('title', issue.title);
            core.setOutput('body', issue.body || '');
            core.setOutput('number', issue.number);

      - name: Determine model and label
        id: config
        run: |
          if [[ "${{ github.event.label.name }}" == "ai-fix-easy" ]]; then
            echo "model=claude-3-5-haiku-20241022" >> $GITHUB_OUTPUT
            echo "label=ai-fix-easy" >> $GITHUB_OUTPUT
          else
            echo "model=claude-sonnet-4-20250514" >> $GITHUB_OUTPUT
            echo "label=ai-fix-hard" >> $GITHUB_OUTPUT
          fi

      - name: Run Claude Code Action with direct prompt
        uses: anthropics/claude-code-action@beta
        with:
          model: ${{ steps.config.outputs.model }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          direct_prompt: |
            Analyze this GitHub issue and create a fix:
            Issue #${{ steps.issue.outputs.number }}: ${{ steps.issue.outputs.title }}
            Description:
            ${{ steps.issue.outputs.body }}
            
            Make sure to:
            1. Understand the problem described in the issue
            2. Locate relevant files that need changes
            3. Implement a proper solution
            4. Create a pull request with the fix
            5. After implementing the fix, comment on the original issue with a summary of what was changed and link to the pull request.

      - name: Remove applied label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: '${{ steps.config.outputs.label }}'
            });
